USE [master]
GO

/****** Object:  Database [rame.study.mock]    Script Date: 15/01/2025 15:27:39 ******/
CREATE DATABASE [rame.study.mock]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'rame.study.mock', FILENAME = N'C:\Users\Rame\rame.study.mock.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'rame.study.mock_log', FILENAME = N'C:\Users\Rame\rame.study.mock_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [rame.study.mock].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [rame.study.mock] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [rame.study.mock] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [rame.study.mock] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [rame.study.mock] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [rame.study.mock] SET ARITHABORT OFF 
GO

ALTER DATABASE [rame.study.mock] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [rame.study.mock] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [rame.study.mock] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [rame.study.mock] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [rame.study.mock] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [rame.study.mock] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [rame.study.mock] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [rame.study.mock] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [rame.study.mock] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [rame.study.mock] SET  DISABLE_BROKER 
GO

ALTER DATABASE [rame.study.mock] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [rame.study.mock] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [rame.study.mock] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [rame.study.mock] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [rame.study.mock] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [rame.study.mock] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [rame.study.mock] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [rame.study.mock] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [rame.study.mock] SET  MULTI_USER 
GO

ALTER DATABASE [rame.study.mock] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [rame.study.mock] SET DB_CHAINING OFF 
GO

ALTER DATABASE [rame.study.mock] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [rame.study.mock] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [rame.study.mock] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [rame.study.mock] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [rame.study.mock] SET QUERY_STORE = OFF
GO

ALTER DATABASE [rame.study.mock] SET  READ_WRITE 
GO

