USE [master]
GO

/****** Object:  Database [rame.study.mockCopy]    Script Date: 15/01/2025 15:38:08 ******/
CREATE DATABASE [rame.study.mockCopy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'rame.study.mockCopy', FILENAME = N'C:\Users\Rame\rame.study.mockCopy.mdf' , SIZE = 335872KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'rame.study.mockCopy_log', FILENAME = N'C:\Users\Rame\rame.study.mockCopy_log.ldf' , SIZE = 401408KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [rame.study.mockCopy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [rame.study.mockCopy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET ARITHABORT OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [rame.study.mockCopy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [rame.study.mockCopy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [rame.study.mockCopy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [rame.study.mockCopy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [rame.study.mockCopy] SET  MULTI_USER 
GO

ALTER DATABASE [rame.study.mockCopy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [rame.study.mockCopy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [rame.study.mockCopy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [rame.study.mockCopy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [rame.study.mockCopy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [rame.study.mockCopy] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [rame.study.mockCopy] SET QUERY_STORE = OFF
GO

ALTER DATABASE [rame.study.mockCopy] SET  READ_WRITE 
GO

